### ISSUE TITLE
add convenience methods

### ISSUE THREAD

**Issue by citizenjosh** [mdemblani/nodejs-freshsales-api#2]
e.g. `freshsales.search(query)`

And thank you for doing this project. It already makes interacting with Freshsales pretty easy.

**Comment by mdemblani** [comment]
@citizenjosh,

The suggestion is good. We can go about providing a few convenience methods for easier usage. However, in providing such methods, we also have to make sure that it remains simple and not confusing for the end user.

Feel free to provide to update the code and submit in a pull request regarding the same

**Comment by citizenjosh** [comment]
Did https://github.com/mdemblani/nodejs-freshsales-api/pull/3 as a first step, @mdemblani. How can I improve them?
This is my first time using Node. 

After this there are several more that I'd like to add.
